# Generated by Django 4.0.4 on 2022-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default='', verbose_name='Дата')),
                ('day', models.CharField(default='', max_length=55, verbose_name='День')),
                ('para1', models.CharField(default='', max_length=55, verbose_name='Первая пара')),
                ('kab1', models.CharField(default='', max_length=55, verbose_name='Кабинет')),
                ('para2', models.CharField(default='', max_length=55, verbose_name='Вторая пара')),
                ('kab2', models.CharField(default='', max_length=55, verbose_name='Кабинет')),
                ('para3', models.CharField(default='', max_length=55, verbose_name='Третья пара')),
                ('kab3', models.CharField(default='', max_length=55, verbose_name='Кабинет')),
                ('para4', models.CharField(default='', max_length=55, verbose_name='Четвертая пара')),
                ('kab4', models.CharField(default='', max_length=55, verbose_name='Кабинет')),
                ('para5', models.CharField(default='', max_length=55, verbose_name='Пятая пара')),
                ('kab5', models.CharField(default='', max_length=55, verbose_name='Кабинет')),
                ('para6', models.CharField(default='', max_length=55, verbose_name='Шестая пара')),
                ('kab6', models.CharField(default='', max_length=55, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Немешаева Анастасия Андреевна',
                'verbose_name_plural': 'Немешаева А.А.',
            },
        ),
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_1', models.DateField(default='', verbose_name='Дата')),
                ('day_1', models.CharField(max_length=55, verbose_name='День')),
                ('para1_1', models.CharField(max_length=55, verbose_name='Первая пара')),
                ('kab1_1', models.CharField(max_length=55, verbose_name='Кабинет')),
                ('para2_1', models.CharField(max_length=55, verbose_name='Вторая пара')),
                ('kab2_1', models.CharField(max_length=55, verbose_name='Кабинет')),
                ('para3_1', models.CharField(max_length=55, verbose_name='Третья пара')),
                ('kab3_1', models.CharField(max_length=55, verbose_name='Кабинет')),
                ('para4_1', models.CharField(max_length=55, verbose_name='Четвертая пара')),
                ('kab4_1', models.CharField(max_length=55, verbose_name='Кабинет')),
                ('para5_1', models.CharField(max_length=55, verbose_name='Пятая пара')),
                ('kab5_1', models.CharField(max_length=55, verbose_name='Кабинет')),
                ('para6_1', models.CharField(max_length=55, verbose_name='Шестая пара')),
                ('kab6_1', models.CharField(max_length=55, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Аминова Анастасия Сергеевна',
                'verbose_name_plural': 'Аминова А.С.',
            },
        ),
    ]
