# Generated by Django 4.0.4 on 2022-05-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Kabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, verbose_name='Название кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=55, verbose_name='Фамилия Преподавателя')),
                ('first_name', models.CharField(default='', max_length=55, verbose_name='Имя Преподавателя')),
                ('third_name', models.CharField(default='', max_length=55, verbose_name='Отчество Преподавателя')),
            ],
            options={
                'verbose_name': 'ФИО Преподавателей',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default='', verbose_name='Номер пары')),
                ('data', models.DateField(default='', max_length=55, verbose_name='Дата пары')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='execute.group')),
                ('kabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='execute.kabinet')),
                ('last_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='execute.prepod')),
            ],
            options={
                'verbose_name': 'Расписание пары',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Task1',
        ),
    ]
