# Generated by Django 4.0.4 on 2022-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execute', '0002_group_kabinet_prepod_raspisanie_delete_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspisanie',
            name='number',
            field=models.CharField(default='', max_length=55, verbose_name='Номер пары'),
        ),
    ]
